// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto;
namespace universe {
class Connect;
struct ConnectDefaultTypeInternal;
extern ConnectDefaultTypeInternal _Connect_default_instance_;
class Envelope;
struct EnvelopeDefaultTypeInternal;
extern EnvelopeDefaultTypeInternal _Envelope_default_instance_;
class Move;
struct MoveDefaultTypeInternal;
extern MoveDefaultTypeInternal _Move_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace universe
PROTOBUF_NAMESPACE_OPEN
template<> ::universe::Connect* Arena::CreateMaybeMessage<::universe::Connect>(Arena*);
template<> ::universe::Envelope* Arena::CreateMaybeMessage<::universe::Envelope>(Arena*);
template<> ::universe::Move* Arena::CreateMaybeMessage<::universe::Move>(Arena*);
template<> ::universe::Response* Arena::CreateMaybeMessage<::universe::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace universe {

// ===================================================================

class Connect final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Connect) */ {
 public:
  inline Connect() : Connect(nullptr) {}
  ~Connect() override;
  explicit PROTOBUF_CONSTEXPR Connect(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Connect(const Connect& from);
  Connect(Connect&& from) noexcept
    : Connect() {
    *this = ::std::move(from);
  }

  inline Connect& operator=(const Connect& from) {
    CopyFrom(from);
    return *this;
  }
  inline Connect& operator=(Connect&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Connect& default_instance() {
    return *internal_default_instance();
  }
  static inline const Connect* internal_default_instance() {
    return reinterpret_cast<const Connect*>(
               &_Connect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Connect& a, Connect& b) {
    a.Swap(&b);
  }
  inline void Swap(Connect* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Connect* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Connect* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Connect>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Connect& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Connect& from) {
    Connect::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Connect* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Connect";
  }
  protected:
  explicit Connect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChFieldNumber = 1,
  };
  // string ch = 1;
  void clear_ch();
  const std::string& ch() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ch(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ch();
  PROTOBUF_NODISCARD std::string* release_ch();
  void set_allocated_ch(std::string* ch);
  private:
  const std::string& _internal_ch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ch(const std::string& value);
  std::string* _internal_mutable_ch();
  public:

  // @@protoc_insertion_point(class_scope:universe.Connect)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Move) */ {
 public:
  inline Move() : Move(nullptr) {}
  ~Move() override;
  explicit PROTOBUF_CONSTEXPR Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Move(const Move& from);
  Move(Move&& from) noexcept
    : Move() {
    *this = ::std::move(from);
  }

  inline Move& operator=(const Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline Move& operator=(Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const Move* internal_default_instance() {
    return reinterpret_cast<const Move*>(
               &_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Move& a, Move& b) {
    a.Swap(&b);
  }
  inline void Swap(Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Move& from) {
    Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Move";
  }
  protected:
  explicit Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChFieldNumber = 1,
    kDirFieldNumber = 2,
  };
  // string ch = 1;
  void clear_ch();
  const std::string& ch() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ch(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ch();
  PROTOBUF_NODISCARD std::string* release_ch();
  void set_allocated_ch(std::string* ch);
  private:
  const std::string& _internal_ch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ch(const std::string& value);
  std::string* _internal_mutable_ch();
  public:

  // string dir = 2;
  void clear_dir();
  const std::string& dir() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dir(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dir();
  PROTOBUF_NODISCARD std::string* release_dir();
  void set_allocated_dir(std::string* dir);
  private:
  const std::string& _internal_dir() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dir(const std::string& value);
  std::string* _internal_mutable_dir();
  public:

  // @@protoc_insertion_point(class_scope:universe.Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ch_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dir_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response& from) {
    Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 1,
  };
  // string text = 1;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // @@protoc_insertion_point(class_scope:universe.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Envelope final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Envelope) */ {
 public:
  inline Envelope() : Envelope(nullptr) {}
  ~Envelope() override;
  explicit PROTOBUF_CONSTEXPR Envelope(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Envelope(const Envelope& from);
  Envelope(Envelope&& from) noexcept
    : Envelope() {
    *this = ::std::move(from);
  }

  inline Envelope& operator=(const Envelope& from) {
    CopyFrom(from);
    return *this;
  }
  inline Envelope& operator=(Envelope&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Envelope& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kConnect = 1,
    kMove = 2,
    kResponse = 3,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const Envelope* internal_default_instance() {
    return reinterpret_cast<const Envelope*>(
               &_Envelope_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Envelope& a, Envelope& b) {
    a.Swap(&b);
  }
  inline void Swap(Envelope* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Envelope* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Envelope* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Envelope>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Envelope& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Envelope& from) {
    Envelope::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Envelope* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Envelope";
  }
  protected:
  explicit Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConnectFieldNumber = 1,
    kMoveFieldNumber = 2,
    kResponseFieldNumber = 3,
  };
  // .universe.Connect connect = 1;
  bool has_connect() const;
  private:
  bool _internal_has_connect() const;
  public:
  void clear_connect();
  const ::universe::Connect& connect() const;
  PROTOBUF_NODISCARD ::universe::Connect* release_connect();
  ::universe::Connect* mutable_connect();
  void set_allocated_connect(::universe::Connect* connect);
  private:
  const ::universe::Connect& _internal_connect() const;
  ::universe::Connect* _internal_mutable_connect();
  public:
  void unsafe_arena_set_allocated_connect(
      ::universe::Connect* connect);
  ::universe::Connect* unsafe_arena_release_connect();

  // .universe.Move move = 2;
  bool has_move() const;
  private:
  bool _internal_has_move() const;
  public:
  void clear_move();
  const ::universe::Move& move() const;
  PROTOBUF_NODISCARD ::universe::Move* release_move();
  ::universe::Move* mutable_move();
  void set_allocated_move(::universe::Move* move);
  private:
  const ::universe::Move& _internal_move() const;
  ::universe::Move* _internal_mutable_move();
  public:
  void unsafe_arena_set_allocated_move(
      ::universe::Move* move);
  ::universe::Move* unsafe_arena_release_move();

  // .universe.Response response = 3;
  bool has_response() const;
  private:
  bool _internal_has_response() const;
  public:
  void clear_response();
  const ::universe::Response& response() const;
  PROTOBUF_NODISCARD ::universe::Response* release_response();
  ::universe::Response* mutable_response();
  void set_allocated_response(::universe::Response* response);
  private:
  const ::universe::Response& _internal_response() const;
  ::universe::Response* _internal_mutable_response();
  public:
  void unsafe_arena_set_allocated_response(
      ::universe::Response* response);
  ::universe::Response* unsafe_arena_release_response();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:universe.Envelope)
 private:
  class _Internal;
  void set_has_connect();
  void set_has_move();
  void set_has_response();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::universe::Connect* connect_;
      ::universe::Move* move_;
      ::universe::Response* response_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Connect

// string ch = 1;
inline void Connect::clear_ch() {
  _impl_.ch_.ClearToEmpty();
}
inline const std::string& Connect::ch() const {
  // @@protoc_insertion_point(field_get:universe.Connect.ch)
  return _internal_ch();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_ch(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ch_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Connect.ch)
}
inline std::string* Connect::mutable_ch() {
  std::string* _s = _internal_mutable_ch();
  // @@protoc_insertion_point(field_mutable:universe.Connect.ch)
  return _s;
}
inline const std::string& Connect::_internal_ch() const {
  return _impl_.ch_.Get();
}
inline void Connect::_internal_set_ch(const std::string& value) {
  
  _impl_.ch_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_ch() {
  
  return _impl_.ch_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_ch() {
  // @@protoc_insertion_point(field_release:universe.Connect.ch)
  return _impl_.ch_.Release();
}
inline void Connect::set_allocated_ch(std::string* ch) {
  if (ch != nullptr) {
    
  } else {
    
  }
  _impl_.ch_.SetAllocated(ch, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ch_.IsDefault()) {
    _impl_.ch_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Connect.ch)
}

// -------------------------------------------------------------------

// Move

// string ch = 1;
inline void Move::clear_ch() {
  _impl_.ch_.ClearToEmpty();
}
inline const std::string& Move::ch() const {
  // @@protoc_insertion_point(field_get:universe.Move.ch)
  return _internal_ch();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Move::set_ch(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ch_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Move.ch)
}
inline std::string* Move::mutable_ch() {
  std::string* _s = _internal_mutable_ch();
  // @@protoc_insertion_point(field_mutable:universe.Move.ch)
  return _s;
}
inline const std::string& Move::_internal_ch() const {
  return _impl_.ch_.Get();
}
inline void Move::_internal_set_ch(const std::string& value) {
  
  _impl_.ch_.Set(value, GetArenaForAllocation());
}
inline std::string* Move::_internal_mutable_ch() {
  
  return _impl_.ch_.Mutable(GetArenaForAllocation());
}
inline std::string* Move::release_ch() {
  // @@protoc_insertion_point(field_release:universe.Move.ch)
  return _impl_.ch_.Release();
}
inline void Move::set_allocated_ch(std::string* ch) {
  if (ch != nullptr) {
    
  } else {
    
  }
  _impl_.ch_.SetAllocated(ch, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ch_.IsDefault()) {
    _impl_.ch_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Move.ch)
}

// string dir = 2;
inline void Move::clear_dir() {
  _impl_.dir_.ClearToEmpty();
}
inline const std::string& Move::dir() const {
  // @@protoc_insertion_point(field_get:universe.Move.dir)
  return _internal_dir();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Move::set_dir(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dir_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Move.dir)
}
inline std::string* Move::mutable_dir() {
  std::string* _s = _internal_mutable_dir();
  // @@protoc_insertion_point(field_mutable:universe.Move.dir)
  return _s;
}
inline const std::string& Move::_internal_dir() const {
  return _impl_.dir_.Get();
}
inline void Move::_internal_set_dir(const std::string& value) {
  
  _impl_.dir_.Set(value, GetArenaForAllocation());
}
inline std::string* Move::_internal_mutable_dir() {
  
  return _impl_.dir_.Mutable(GetArenaForAllocation());
}
inline std::string* Move::release_dir() {
  // @@protoc_insertion_point(field_release:universe.Move.dir)
  return _impl_.dir_.Release();
}
inline void Move::set_allocated_dir(std::string* dir) {
  if (dir != nullptr) {
    
  } else {
    
  }
  _impl_.dir_.SetAllocated(dir, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dir_.IsDefault()) {
    _impl_.dir_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Move.dir)
}

// -------------------------------------------------------------------

// Response

// string text = 1;
inline void Response::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& Response::text() const {
  // @@protoc_insertion_point(field_get:universe.Response.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Response::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Response.text)
}
inline std::string* Response::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:universe.Response.text)
  return _s;
}
inline const std::string& Response::_internal_text() const {
  return _impl_.text_.Get();
}
inline void Response::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* Response::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* Response::release_text() {
  // @@protoc_insertion_point(field_release:universe.Response.text)
  return _impl_.text_.Release();
}
inline void Response::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Response.text)
}

// -------------------------------------------------------------------

// Envelope

// .universe.Connect connect = 1;
inline bool Envelope::_internal_has_connect() const {
  return payload_case() == kConnect;
}
inline bool Envelope::has_connect() const {
  return _internal_has_connect();
}
inline void Envelope::set_has_connect() {
  _impl_._oneof_case_[0] = kConnect;
}
inline void Envelope::clear_connect() {
  if (_internal_has_connect()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.connect_;
    }
    clear_has_payload();
  }
}
inline ::universe::Connect* Envelope::release_connect() {
  // @@protoc_insertion_point(field_release:universe.Envelope.connect)
  if (_internal_has_connect()) {
    clear_has_payload();
    ::universe::Connect* temp = _impl_.payload_.connect_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::Connect& Envelope::_internal_connect() const {
  return _internal_has_connect()
      ? *_impl_.payload_.connect_
      : reinterpret_cast< ::universe::Connect&>(::universe::_Connect_default_instance_);
}
inline const ::universe::Connect& Envelope::connect() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.connect)
  return _internal_connect();
}
inline ::universe::Connect* Envelope::unsafe_arena_release_connect() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.connect)
  if (_internal_has_connect()) {
    clear_has_payload();
    ::universe::Connect* temp = _impl_.payload_.connect_;
    _impl_.payload_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_connect(::universe::Connect* connect) {
  clear_payload();
  if (connect) {
    set_has_connect();
    _impl_.payload_.connect_ = connect;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.connect)
}
inline ::universe::Connect* Envelope::_internal_mutable_connect() {
  if (!_internal_has_connect()) {
    clear_payload();
    set_has_connect();
    _impl_.payload_.connect_ = CreateMaybeMessage< ::universe::Connect >(GetArenaForAllocation());
  }
  return _impl_.payload_.connect_;
}
inline ::universe::Connect* Envelope::mutable_connect() {
  ::universe::Connect* _msg = _internal_mutable_connect();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.connect)
  return _msg;
}

// .universe.Move move = 2;
inline bool Envelope::_internal_has_move() const {
  return payload_case() == kMove;
}
inline bool Envelope::has_move() const {
  return _internal_has_move();
}
inline void Envelope::set_has_move() {
  _impl_._oneof_case_[0] = kMove;
}
inline void Envelope::clear_move() {
  if (_internal_has_move()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.move_;
    }
    clear_has_payload();
  }
}
inline ::universe::Move* Envelope::release_move() {
  // @@protoc_insertion_point(field_release:universe.Envelope.move)
  if (_internal_has_move()) {
    clear_has_payload();
    ::universe::Move* temp = _impl_.payload_.move_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::Move& Envelope::_internal_move() const {
  return _internal_has_move()
      ? *_impl_.payload_.move_
      : reinterpret_cast< ::universe::Move&>(::universe::_Move_default_instance_);
}
inline const ::universe::Move& Envelope::move() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.move)
  return _internal_move();
}
inline ::universe::Move* Envelope::unsafe_arena_release_move() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.move)
  if (_internal_has_move()) {
    clear_has_payload();
    ::universe::Move* temp = _impl_.payload_.move_;
    _impl_.payload_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_move(::universe::Move* move) {
  clear_payload();
  if (move) {
    set_has_move();
    _impl_.payload_.move_ = move;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.move)
}
inline ::universe::Move* Envelope::_internal_mutable_move() {
  if (!_internal_has_move()) {
    clear_payload();
    set_has_move();
    _impl_.payload_.move_ = CreateMaybeMessage< ::universe::Move >(GetArenaForAllocation());
  }
  return _impl_.payload_.move_;
}
inline ::universe::Move* Envelope::mutable_move() {
  ::universe::Move* _msg = _internal_mutable_move();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.move)
  return _msg;
}

// .universe.Response response = 3;
inline bool Envelope::_internal_has_response() const {
  return payload_case() == kResponse;
}
inline bool Envelope::has_response() const {
  return _internal_has_response();
}
inline void Envelope::set_has_response() {
  _impl_._oneof_case_[0] = kResponse;
}
inline void Envelope::clear_response() {
  if (_internal_has_response()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.response_;
    }
    clear_has_payload();
  }
}
inline ::universe::Response* Envelope::release_response() {
  // @@protoc_insertion_point(field_release:universe.Envelope.response)
  if (_internal_has_response()) {
    clear_has_payload();
    ::universe::Response* temp = _impl_.payload_.response_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::Response& Envelope::_internal_response() const {
  return _internal_has_response()
      ? *_impl_.payload_.response_
      : reinterpret_cast< ::universe::Response&>(::universe::_Response_default_instance_);
}
inline const ::universe::Response& Envelope::response() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.response)
  return _internal_response();
}
inline ::universe::Response* Envelope::unsafe_arena_release_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.response)
  if (_internal_has_response()) {
    clear_has_payload();
    ::universe::Response* temp = _impl_.payload_.response_;
    _impl_.payload_.response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_response(::universe::Response* response) {
  clear_payload();
  if (response) {
    set_has_response();
    _impl_.payload_.response_ = response;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.response)
}
inline ::universe::Response* Envelope::_internal_mutable_response() {
  if (!_internal_has_response()) {
    clear_payload();
    set_has_response();
    _impl_.payload_.response_ = CreateMaybeMessage< ::universe::Response >(GetArenaForAllocation());
  }
  return _impl_.payload_.response_;
}
inline ::universe::Response* Envelope::mutable_response() {
  ::universe::Response* _msg = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.response)
  return _msg;
}

inline bool Envelope::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Envelope::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Envelope::PayloadCase Envelope::payload_case() const {
  return Envelope::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace universe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
