// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fmessages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fmessages_2eproto;
namespace universe {
class Connect;
struct ConnectDefaultTypeInternal;
extern ConnectDefaultTypeInternal _Connect_default_instance_;
class Envelope;
struct EnvelopeDefaultTypeInternal;
extern EnvelopeDefaultTypeInternal _Envelope_default_instance_;
class GameState;
struct GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class Move;
struct MoveDefaultTypeInternal;
extern MoveDefaultTypeInternal _Move_default_instance_;
class Planet;
struct PlanetDefaultTypeInternal;
extern PlanetDefaultTypeInternal _Planet_default_instance_;
class Position;
struct PositionDefaultTypeInternal;
extern PositionDefaultTypeInternal _Position_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Ship;
struct ShipDefaultTypeInternal;
extern ShipDefaultTypeInternal _Ship_default_instance_;
class Trash;
struct TrashDefaultTypeInternal;
extern TrashDefaultTypeInternal _Trash_default_instance_;
}  // namespace universe
PROTOBUF_NAMESPACE_OPEN
template<> ::universe::Connect* Arena::CreateMaybeMessage<::universe::Connect>(Arena*);
template<> ::universe::Envelope* Arena::CreateMaybeMessage<::universe::Envelope>(Arena*);
template<> ::universe::GameState* Arena::CreateMaybeMessage<::universe::GameState>(Arena*);
template<> ::universe::Move* Arena::CreateMaybeMessage<::universe::Move>(Arena*);
template<> ::universe::Planet* Arena::CreateMaybeMessage<::universe::Planet>(Arena*);
template<> ::universe::Position* Arena::CreateMaybeMessage<::universe::Position>(Arena*);
template<> ::universe::Response* Arena::CreateMaybeMessage<::universe::Response>(Arena*);
template<> ::universe::Ship* Arena::CreateMaybeMessage<::universe::Ship>(Arena*);
template<> ::universe::Trash* Arena::CreateMaybeMessage<::universe::Trash>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace universe {

// ===================================================================

class Connect final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Connect) */ {
 public:
  inline Connect() : Connect(nullptr) {}
  ~Connect() override;
  explicit PROTOBUF_CONSTEXPR Connect(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Connect(const Connect& from);
  Connect(Connect&& from) noexcept
    : Connect() {
    *this = ::std::move(from);
  }

  inline Connect& operator=(const Connect& from) {
    CopyFrom(from);
    return *this;
  }
  inline Connect& operator=(Connect&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Connect& default_instance() {
    return *internal_default_instance();
  }
  static inline const Connect* internal_default_instance() {
    return reinterpret_cast<const Connect*>(
               &_Connect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Connect& a, Connect& b) {
    a.Swap(&b);
  }
  inline void Swap(Connect* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Connect* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Connect* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Connect>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Connect& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Connect& from) {
    Connect::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Connect* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Connect";
  }
  protected:
  explicit Connect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChFieldNumber = 1,
  };
  // string ch = 1;
  void clear_ch();
  const std::string& ch() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ch(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ch();
  PROTOBUF_NODISCARD std::string* release_ch();
  void set_allocated_ch(std::string* ch);
  private:
  const std::string& _internal_ch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ch(const std::string& value);
  std::string* _internal_mutable_ch();
  public:

  // @@protoc_insertion_point(class_scope:universe.Connect)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ch_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Position final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Position) */ {
 public:
  inline Position() : Position(nullptr) {}
  ~Position() override;
  explicit PROTOBUF_CONSTEXPR Position(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Position(const Position& from);
  Position(Position&& from) noexcept
    : Position() {
    *this = ::std::move(from);
  }

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline Position& operator=(Position&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Position& default_instance() {
    return *internal_default_instance();
  }
  static inline const Position* internal_default_instance() {
    return reinterpret_cast<const Position*>(
               &_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Position& a, Position& b) {
    a.Swap(&b);
  }
  inline void Swap(Position* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Position* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Position>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Position& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Position& from) {
    Position::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Position* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Position";
  }
  protected:
  explicit Position(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 2;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:universe.Position)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t x_;
    int32_t y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Move) */ {
 public:
  inline Move() : Move(nullptr) {}
  ~Move() override;
  explicit PROTOBUF_CONSTEXPR Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Move(const Move& from);
  Move(Move&& from) noexcept
    : Move() {
    *this = ::std::move(from);
  }

  inline Move& operator=(const Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline Move& operator=(Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const Move* internal_default_instance() {
    return reinterpret_cast<const Move*>(
               &_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Move& a, Move& b) {
    a.Swap(&b);
  }
  inline void Swap(Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Move& from) {
    Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Move";
  }
  protected:
  explicit Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChFieldNumber = 1,
    kDirFieldNumber = 2,
  };
  // string ch = 1;
  void clear_ch();
  const std::string& ch() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ch(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ch();
  PROTOBUF_NODISCARD std::string* release_ch();
  void set_allocated_ch(std::string* ch);
  private:
  const std::string& _internal_ch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ch(const std::string& value);
  std::string* _internal_mutable_ch();
  public:

  // string dir = 2;
  void clear_dir();
  const std::string& dir() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dir(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dir();
  PROTOBUF_NODISCARD std::string* release_dir();
  void set_allocated_dir(std::string* dir);
  private:
  const std::string& _internal_dir() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dir(const std::string& value);
  std::string* _internal_mutable_dir();
  public:

  // @@protoc_insertion_point(class_scope:universe.Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ch_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dir_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Response& from) {
    Response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 1,
  };
  // string text = 1;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // @@protoc_insertion_point(class_scope:universe.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Ship final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Ship) */ {
 public:
  inline Ship() : Ship(nullptr) {}
  ~Ship() override;
  explicit PROTOBUF_CONSTEXPR Ship(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ship(const Ship& from);
  Ship(Ship&& from) noexcept
    : Ship() {
    *this = ::std::move(from);
  }

  inline Ship& operator=(const Ship& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ship& operator=(Ship&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ship& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ship* internal_default_instance() {
    return reinterpret_cast<const Ship*>(
               &_Ship_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Ship& a, Ship& b) {
    a.Swap(&b);
  }
  inline void Swap(Ship* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ship* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ship* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ship>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ship& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Ship& from) {
    Ship::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ship* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Ship";
  }
  protected:
  explicit Ship(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChFieldNumber = 1,
    kPosFieldNumber = 2,
    kTrashCountFieldNumber = 3,
  };
  // string ch = 1;
  void clear_ch();
  const std::string& ch() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ch(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ch();
  PROTOBUF_NODISCARD std::string* release_ch();
  void set_allocated_ch(std::string* ch);
  private:
  const std::string& _internal_ch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ch(const std::string& value);
  std::string* _internal_mutable_ch();
  public:

  // .universe.Position pos = 2;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::universe::Position& pos() const;
  PROTOBUF_NODISCARD ::universe::Position* release_pos();
  ::universe::Position* mutable_pos();
  void set_allocated_pos(::universe::Position* pos);
  private:
  const ::universe::Position& _internal_pos() const;
  ::universe::Position* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::universe::Position* pos);
  ::universe::Position* unsafe_arena_release_pos();

  // int32 trash_count = 3;
  void clear_trash_count();
  int32_t trash_count() const;
  void set_trash_count(int32_t value);
  private:
  int32_t _internal_trash_count() const;
  void _internal_set_trash_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:universe.Ship)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ch_;
    ::universe::Position* pos_;
    int32_t trash_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Planet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Planet) */ {
 public:
  inline Planet() : Planet(nullptr) {}
  ~Planet() override;
  explicit PROTOBUF_CONSTEXPR Planet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Planet(const Planet& from);
  Planet(Planet&& from) noexcept
    : Planet() {
    *this = ::std::move(from);
  }

  inline Planet& operator=(const Planet& from) {
    CopyFrom(from);
    return *this;
  }
  inline Planet& operator=(Planet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Planet& default_instance() {
    return *internal_default_instance();
  }
  static inline const Planet* internal_default_instance() {
    return reinterpret_cast<const Planet*>(
               &_Planet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Planet& a, Planet& b) {
    a.Swap(&b);
  }
  inline void Swap(Planet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Planet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Planet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Planet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Planet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Planet& from) {
    Planet::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Planet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Planet";
  }
  protected:
  explicit Planet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kPosFieldNumber = 2,
    kTrashCountFieldNumber = 3,
    kIsGarbageFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .universe.Position pos = 2;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::universe::Position& pos() const;
  PROTOBUF_NODISCARD ::universe::Position* release_pos();
  ::universe::Position* mutable_pos();
  void set_allocated_pos(::universe::Position* pos);
  private:
  const ::universe::Position& _internal_pos() const;
  ::universe::Position* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::universe::Position* pos);
  ::universe::Position* unsafe_arena_release_pos();

  // int32 trash_count = 3;
  void clear_trash_count();
  int32_t trash_count() const;
  void set_trash_count(int32_t value);
  private:
  int32_t _internal_trash_count() const;
  void _internal_set_trash_count(int32_t value);
  public:

  // bool is_garbage = 4;
  void clear_is_garbage();
  bool is_garbage() const;
  void set_is_garbage(bool value);
  private:
  bool _internal_is_garbage() const;
  void _internal_set_is_garbage(bool value);
  public:

  // @@protoc_insertion_point(class_scope:universe.Planet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::universe::Position* pos_;
    int32_t trash_count_;
    bool is_garbage_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Trash final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Trash) */ {
 public:
  inline Trash() : Trash(nullptr) {}
  ~Trash() override;
  explicit PROTOBUF_CONSTEXPR Trash(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Trash(const Trash& from);
  Trash(Trash&& from) noexcept
    : Trash() {
    *this = ::std::move(from);
  }

  inline Trash& operator=(const Trash& from) {
    CopyFrom(from);
    return *this;
  }
  inline Trash& operator=(Trash&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Trash& default_instance() {
    return *internal_default_instance();
  }
  static inline const Trash* internal_default_instance() {
    return reinterpret_cast<const Trash*>(
               &_Trash_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Trash& a, Trash& b) {
    a.Swap(&b);
  }
  inline void Swap(Trash* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Trash* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Trash* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Trash>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Trash& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Trash& from) {
    Trash::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Trash* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Trash";
  }
  protected:
  explicit Trash(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 1,
  };
  // .universe.Position pos = 1;
  bool has_pos() const;
  private:
  bool _internal_has_pos() const;
  public:
  void clear_pos();
  const ::universe::Position& pos() const;
  PROTOBUF_NODISCARD ::universe::Position* release_pos();
  ::universe::Position* mutable_pos();
  void set_allocated_pos(::universe::Position* pos);
  private:
  const ::universe::Position& _internal_pos() const;
  ::universe::Position* _internal_mutable_pos();
  public:
  void unsafe_arena_set_allocated_pos(
      ::universe::Position* pos);
  ::universe::Position* unsafe_arena_release_pos();

  // @@protoc_insertion_point(class_scope:universe.Trash)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::universe::Position* pos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class GameState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.GameState) */ {
 public:
  inline GameState() : GameState(nullptr) {}
  ~GameState() override;
  explicit PROTOBUF_CONSTEXPR GameState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameState(const GameState& from);
  GameState(GameState&& from) noexcept
    : GameState() {
    *this = ::std::move(from);
  }

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameState& operator=(GameState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameState& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GameState& a, GameState& b) {
    a.Swap(&b);
  }
  inline void Swap(GameState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameState& from) {
    GameState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.GameState";
  }
  protected:
  explicit GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShipsFieldNumber = 1,
    kPlanetsFieldNumber = 2,
    kTrashFieldNumber = 3,
    kTotalTrashFieldNumber = 4,
  };
  // repeated .universe.Ship ships = 1;
  int ships_size() const;
  private:
  int _internal_ships_size() const;
  public:
  void clear_ships();
  ::universe::Ship* mutable_ships(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Ship >*
      mutable_ships();
  private:
  const ::universe::Ship& _internal_ships(int index) const;
  ::universe::Ship* _internal_add_ships();
  public:
  const ::universe::Ship& ships(int index) const;
  ::universe::Ship* add_ships();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Ship >&
      ships() const;

  // repeated .universe.Planet planets = 2;
  int planets_size() const;
  private:
  int _internal_planets_size() const;
  public:
  void clear_planets();
  ::universe::Planet* mutable_planets(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Planet >*
      mutable_planets();
  private:
  const ::universe::Planet& _internal_planets(int index) const;
  ::universe::Planet* _internal_add_planets();
  public:
  const ::universe::Planet& planets(int index) const;
  ::universe::Planet* add_planets();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Planet >&
      planets() const;

  // repeated .universe.Trash trash = 3;
  int trash_size() const;
  private:
  int _internal_trash_size() const;
  public:
  void clear_trash();
  ::universe::Trash* mutable_trash(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Trash >*
      mutable_trash();
  private:
  const ::universe::Trash& _internal_trash(int index) const;
  ::universe::Trash* _internal_add_trash();
  public:
  const ::universe::Trash& trash(int index) const;
  ::universe::Trash* add_trash();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Trash >&
      trash() const;

  // int32 total_trash = 4;
  void clear_total_trash();
  int32_t total_trash() const;
  void set_total_trash(int32_t value);
  private:
  int32_t _internal_total_trash() const;
  void _internal_set_total_trash(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:universe.GameState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Ship > ships_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Planet > planets_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Trash > trash_;
    int32_t total_trash_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// -------------------------------------------------------------------

class Envelope final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:universe.Envelope) */ {
 public:
  inline Envelope() : Envelope(nullptr) {}
  ~Envelope() override;
  explicit PROTOBUF_CONSTEXPR Envelope(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Envelope(const Envelope& from);
  Envelope(Envelope&& from) noexcept
    : Envelope() {
    *this = ::std::move(from);
  }

  inline Envelope& operator=(const Envelope& from) {
    CopyFrom(from);
    return *this;
  }
  inline Envelope& operator=(Envelope&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Envelope& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kConnect = 1,
    kMove = 2,
    kResponse = 3,
    kGameState = 4,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const Envelope* internal_default_instance() {
    return reinterpret_cast<const Envelope*>(
               &_Envelope_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(Envelope& a, Envelope& b) {
    a.Swap(&b);
  }
  inline void Swap(Envelope* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Envelope* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Envelope* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Envelope>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Envelope& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Envelope& from) {
    Envelope::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Envelope* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "universe.Envelope";
  }
  protected:
  explicit Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConnectFieldNumber = 1,
    kMoveFieldNumber = 2,
    kResponseFieldNumber = 3,
    kGameStateFieldNumber = 4,
  };
  // .universe.Connect connect = 1;
  bool has_connect() const;
  private:
  bool _internal_has_connect() const;
  public:
  void clear_connect();
  const ::universe::Connect& connect() const;
  PROTOBUF_NODISCARD ::universe::Connect* release_connect();
  ::universe::Connect* mutable_connect();
  void set_allocated_connect(::universe::Connect* connect);
  private:
  const ::universe::Connect& _internal_connect() const;
  ::universe::Connect* _internal_mutable_connect();
  public:
  void unsafe_arena_set_allocated_connect(
      ::universe::Connect* connect);
  ::universe::Connect* unsafe_arena_release_connect();

  // .universe.Move move = 2;
  bool has_move() const;
  private:
  bool _internal_has_move() const;
  public:
  void clear_move();
  const ::universe::Move& move() const;
  PROTOBUF_NODISCARD ::universe::Move* release_move();
  ::universe::Move* mutable_move();
  void set_allocated_move(::universe::Move* move);
  private:
  const ::universe::Move& _internal_move() const;
  ::universe::Move* _internal_mutable_move();
  public:
  void unsafe_arena_set_allocated_move(
      ::universe::Move* move);
  ::universe::Move* unsafe_arena_release_move();

  // .universe.Response response = 3;
  bool has_response() const;
  private:
  bool _internal_has_response() const;
  public:
  void clear_response();
  const ::universe::Response& response() const;
  PROTOBUF_NODISCARD ::universe::Response* release_response();
  ::universe::Response* mutable_response();
  void set_allocated_response(::universe::Response* response);
  private:
  const ::universe::Response& _internal_response() const;
  ::universe::Response* _internal_mutable_response();
  public:
  void unsafe_arena_set_allocated_response(
      ::universe::Response* response);
  ::universe::Response* unsafe_arena_release_response();

  // .universe.GameState game_state = 4;
  bool has_game_state() const;
  private:
  bool _internal_has_game_state() const;
  public:
  void clear_game_state();
  const ::universe::GameState& game_state() const;
  PROTOBUF_NODISCARD ::universe::GameState* release_game_state();
  ::universe::GameState* mutable_game_state();
  void set_allocated_game_state(::universe::GameState* game_state);
  private:
  const ::universe::GameState& _internal_game_state() const;
  ::universe::GameState* _internal_mutable_game_state();
  public:
  void unsafe_arena_set_allocated_game_state(
      ::universe::GameState* game_state);
  ::universe::GameState* unsafe_arena_release_game_state();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:universe.Envelope)
 private:
  class _Internal;
  void set_has_connect();
  void set_has_move();
  void set_has_response();
  void set_has_game_state();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::universe::Connect* connect_;
      ::universe::Move* move_;
      ::universe::Response* response_;
      ::universe::GameState* game_state_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Connect

// string ch = 1;
inline void Connect::clear_ch() {
  _impl_.ch_.ClearToEmpty();
}
inline const std::string& Connect::ch() const {
  // @@protoc_insertion_point(field_get:universe.Connect.ch)
  return _internal_ch();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Connect::set_ch(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ch_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Connect.ch)
}
inline std::string* Connect::mutable_ch() {
  std::string* _s = _internal_mutable_ch();
  // @@protoc_insertion_point(field_mutable:universe.Connect.ch)
  return _s;
}
inline const std::string& Connect::_internal_ch() const {
  return _impl_.ch_.Get();
}
inline void Connect::_internal_set_ch(const std::string& value) {
  
  _impl_.ch_.Set(value, GetArenaForAllocation());
}
inline std::string* Connect::_internal_mutable_ch() {
  
  return _impl_.ch_.Mutable(GetArenaForAllocation());
}
inline std::string* Connect::release_ch() {
  // @@protoc_insertion_point(field_release:universe.Connect.ch)
  return _impl_.ch_.Release();
}
inline void Connect::set_allocated_ch(std::string* ch) {
  if (ch != nullptr) {
    
  } else {
    
  }
  _impl_.ch_.SetAllocated(ch, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ch_.IsDefault()) {
    _impl_.ch_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Connect.ch)
}

// -------------------------------------------------------------------

// Position

// int32 x = 1;
inline void Position::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t Position::_internal_x() const {
  return _impl_.x_;
}
inline int32_t Position::x() const {
  // @@protoc_insertion_point(field_get:universe.Position.x)
  return _internal_x();
}
inline void Position::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void Position::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:universe.Position.x)
}

// int32 y = 2;
inline void Position::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t Position::_internal_y() const {
  return _impl_.y_;
}
inline int32_t Position::y() const {
  // @@protoc_insertion_point(field_get:universe.Position.y)
  return _internal_y();
}
inline void Position::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void Position::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:universe.Position.y)
}

// -------------------------------------------------------------------

// Move

// string ch = 1;
inline void Move::clear_ch() {
  _impl_.ch_.ClearToEmpty();
}
inline const std::string& Move::ch() const {
  // @@protoc_insertion_point(field_get:universe.Move.ch)
  return _internal_ch();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Move::set_ch(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ch_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Move.ch)
}
inline std::string* Move::mutable_ch() {
  std::string* _s = _internal_mutable_ch();
  // @@protoc_insertion_point(field_mutable:universe.Move.ch)
  return _s;
}
inline const std::string& Move::_internal_ch() const {
  return _impl_.ch_.Get();
}
inline void Move::_internal_set_ch(const std::string& value) {
  
  _impl_.ch_.Set(value, GetArenaForAllocation());
}
inline std::string* Move::_internal_mutable_ch() {
  
  return _impl_.ch_.Mutable(GetArenaForAllocation());
}
inline std::string* Move::release_ch() {
  // @@protoc_insertion_point(field_release:universe.Move.ch)
  return _impl_.ch_.Release();
}
inline void Move::set_allocated_ch(std::string* ch) {
  if (ch != nullptr) {
    
  } else {
    
  }
  _impl_.ch_.SetAllocated(ch, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ch_.IsDefault()) {
    _impl_.ch_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Move.ch)
}

// string dir = 2;
inline void Move::clear_dir() {
  _impl_.dir_.ClearToEmpty();
}
inline const std::string& Move::dir() const {
  // @@protoc_insertion_point(field_get:universe.Move.dir)
  return _internal_dir();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Move::set_dir(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dir_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Move.dir)
}
inline std::string* Move::mutable_dir() {
  std::string* _s = _internal_mutable_dir();
  // @@protoc_insertion_point(field_mutable:universe.Move.dir)
  return _s;
}
inline const std::string& Move::_internal_dir() const {
  return _impl_.dir_.Get();
}
inline void Move::_internal_set_dir(const std::string& value) {
  
  _impl_.dir_.Set(value, GetArenaForAllocation());
}
inline std::string* Move::_internal_mutable_dir() {
  
  return _impl_.dir_.Mutable(GetArenaForAllocation());
}
inline std::string* Move::release_dir() {
  // @@protoc_insertion_point(field_release:universe.Move.dir)
  return _impl_.dir_.Release();
}
inline void Move::set_allocated_dir(std::string* dir) {
  if (dir != nullptr) {
    
  } else {
    
  }
  _impl_.dir_.SetAllocated(dir, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dir_.IsDefault()) {
    _impl_.dir_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Move.dir)
}

// -------------------------------------------------------------------

// Response

// string text = 1;
inline void Response::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& Response::text() const {
  // @@protoc_insertion_point(field_get:universe.Response.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Response::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Response.text)
}
inline std::string* Response::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:universe.Response.text)
  return _s;
}
inline const std::string& Response::_internal_text() const {
  return _impl_.text_.Get();
}
inline void Response::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* Response::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* Response::release_text() {
  // @@protoc_insertion_point(field_release:universe.Response.text)
  return _impl_.text_.Release();
}
inline void Response::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Response.text)
}

// -------------------------------------------------------------------

// Ship

// string ch = 1;
inline void Ship::clear_ch() {
  _impl_.ch_.ClearToEmpty();
}
inline const std::string& Ship::ch() const {
  // @@protoc_insertion_point(field_get:universe.Ship.ch)
  return _internal_ch();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Ship::set_ch(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ch_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Ship.ch)
}
inline std::string* Ship::mutable_ch() {
  std::string* _s = _internal_mutable_ch();
  // @@protoc_insertion_point(field_mutable:universe.Ship.ch)
  return _s;
}
inline const std::string& Ship::_internal_ch() const {
  return _impl_.ch_.Get();
}
inline void Ship::_internal_set_ch(const std::string& value) {
  
  _impl_.ch_.Set(value, GetArenaForAllocation());
}
inline std::string* Ship::_internal_mutable_ch() {
  
  return _impl_.ch_.Mutable(GetArenaForAllocation());
}
inline std::string* Ship::release_ch() {
  // @@protoc_insertion_point(field_release:universe.Ship.ch)
  return _impl_.ch_.Release();
}
inline void Ship::set_allocated_ch(std::string* ch) {
  if (ch != nullptr) {
    
  } else {
    
  }
  _impl_.ch_.SetAllocated(ch, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ch_.IsDefault()) {
    _impl_.ch_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Ship.ch)
}

// .universe.Position pos = 2;
inline bool Ship::_internal_has_pos() const {
  return this != internal_default_instance() && _impl_.pos_ != nullptr;
}
inline bool Ship::has_pos() const {
  return _internal_has_pos();
}
inline void Ship::clear_pos() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
}
inline const ::universe::Position& Ship::_internal_pos() const {
  const ::universe::Position* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::universe::Position&>(
      ::universe::_Position_default_instance_);
}
inline const ::universe::Position& Ship::pos() const {
  // @@protoc_insertion_point(field_get:universe.Ship.pos)
  return _internal_pos();
}
inline void Ship::unsafe_arena_set_allocated_pos(
    ::universe::Position* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Ship.pos)
}
inline ::universe::Position* Ship::release_pos() {
  
  ::universe::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::universe::Position* Ship::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:universe.Ship.pos)
  
  ::universe::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::universe::Position* Ship::_internal_mutable_pos() {
  
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::universe::Position>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::universe::Position* Ship::mutable_pos() {
  ::universe::Position* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:universe.Ship.pos)
  return _msg;
}
inline void Ship::set_allocated_pos(::universe::Position* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pos_;
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos);
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:universe.Ship.pos)
}

// int32 trash_count = 3;
inline void Ship::clear_trash_count() {
  _impl_.trash_count_ = 0;
}
inline int32_t Ship::_internal_trash_count() const {
  return _impl_.trash_count_;
}
inline int32_t Ship::trash_count() const {
  // @@protoc_insertion_point(field_get:universe.Ship.trash_count)
  return _internal_trash_count();
}
inline void Ship::_internal_set_trash_count(int32_t value) {
  
  _impl_.trash_count_ = value;
}
inline void Ship::set_trash_count(int32_t value) {
  _internal_set_trash_count(value);
  // @@protoc_insertion_point(field_set:universe.Ship.trash_count)
}

// -------------------------------------------------------------------

// Planet

// string name = 1;
inline void Planet::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Planet::name() const {
  // @@protoc_insertion_point(field_get:universe.Planet.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Planet::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:universe.Planet.name)
}
inline std::string* Planet::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:universe.Planet.name)
  return _s;
}
inline const std::string& Planet::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Planet::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Planet::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Planet::release_name() {
  // @@protoc_insertion_point(field_release:universe.Planet.name)
  return _impl_.name_.Release();
}
inline void Planet::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:universe.Planet.name)
}

// .universe.Position pos = 2;
inline bool Planet::_internal_has_pos() const {
  return this != internal_default_instance() && _impl_.pos_ != nullptr;
}
inline bool Planet::has_pos() const {
  return _internal_has_pos();
}
inline void Planet::clear_pos() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
}
inline const ::universe::Position& Planet::_internal_pos() const {
  const ::universe::Position* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::universe::Position&>(
      ::universe::_Position_default_instance_);
}
inline const ::universe::Position& Planet::pos() const {
  // @@protoc_insertion_point(field_get:universe.Planet.pos)
  return _internal_pos();
}
inline void Planet::unsafe_arena_set_allocated_pos(
    ::universe::Position* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Planet.pos)
}
inline ::universe::Position* Planet::release_pos() {
  
  ::universe::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::universe::Position* Planet::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:universe.Planet.pos)
  
  ::universe::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::universe::Position* Planet::_internal_mutable_pos() {
  
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::universe::Position>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::universe::Position* Planet::mutable_pos() {
  ::universe::Position* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:universe.Planet.pos)
  return _msg;
}
inline void Planet::set_allocated_pos(::universe::Position* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pos_;
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos);
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:universe.Planet.pos)
}

// int32 trash_count = 3;
inline void Planet::clear_trash_count() {
  _impl_.trash_count_ = 0;
}
inline int32_t Planet::_internal_trash_count() const {
  return _impl_.trash_count_;
}
inline int32_t Planet::trash_count() const {
  // @@protoc_insertion_point(field_get:universe.Planet.trash_count)
  return _internal_trash_count();
}
inline void Planet::_internal_set_trash_count(int32_t value) {
  
  _impl_.trash_count_ = value;
}
inline void Planet::set_trash_count(int32_t value) {
  _internal_set_trash_count(value);
  // @@protoc_insertion_point(field_set:universe.Planet.trash_count)
}

// bool is_garbage = 4;
inline void Planet::clear_is_garbage() {
  _impl_.is_garbage_ = false;
}
inline bool Planet::_internal_is_garbage() const {
  return _impl_.is_garbage_;
}
inline bool Planet::is_garbage() const {
  // @@protoc_insertion_point(field_get:universe.Planet.is_garbage)
  return _internal_is_garbage();
}
inline void Planet::_internal_set_is_garbage(bool value) {
  
  _impl_.is_garbage_ = value;
}
inline void Planet::set_is_garbage(bool value) {
  _internal_set_is_garbage(value);
  // @@protoc_insertion_point(field_set:universe.Planet.is_garbage)
}

// -------------------------------------------------------------------

// Trash

// .universe.Position pos = 1;
inline bool Trash::_internal_has_pos() const {
  return this != internal_default_instance() && _impl_.pos_ != nullptr;
}
inline bool Trash::has_pos() const {
  return _internal_has_pos();
}
inline void Trash::clear_pos() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_ != nullptr) {
    delete _impl_.pos_;
  }
  _impl_.pos_ = nullptr;
}
inline const ::universe::Position& Trash::_internal_pos() const {
  const ::universe::Position* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::universe::Position&>(
      ::universe::_Position_default_instance_);
}
inline const ::universe::Position& Trash::pos() const {
  // @@protoc_insertion_point(field_get:universe.Trash.pos)
  return _internal_pos();
}
inline void Trash::unsafe_arena_set_allocated_pos(
    ::universe::Position* pos) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Trash.pos)
}
inline ::universe::Position* Trash::release_pos() {
  
  ::universe::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::universe::Position* Trash::unsafe_arena_release_pos() {
  // @@protoc_insertion_point(field_release:universe.Trash.pos)
  
  ::universe::Position* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::universe::Position* Trash::_internal_mutable_pos() {
  
  if (_impl_.pos_ == nullptr) {
    auto* p = CreateMaybeMessage<::universe::Position>(GetArenaForAllocation());
    _impl_.pos_ = p;
  }
  return _impl_.pos_;
}
inline ::universe::Position* Trash::mutable_pos() {
  ::universe::Position* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:universe.Trash.pos)
  return _msg;
}
inline void Trash::set_allocated_pos(::universe::Position* pos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pos_;
  }
  if (pos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos);
    if (message_arena != submessage_arena) {
      pos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_ = pos;
  // @@protoc_insertion_point(field_set_allocated:universe.Trash.pos)
}

// -------------------------------------------------------------------

// GameState

// repeated .universe.Ship ships = 1;
inline int GameState::_internal_ships_size() const {
  return _impl_.ships_.size();
}
inline int GameState::ships_size() const {
  return _internal_ships_size();
}
inline void GameState::clear_ships() {
  _impl_.ships_.Clear();
}
inline ::universe::Ship* GameState::mutable_ships(int index) {
  // @@protoc_insertion_point(field_mutable:universe.GameState.ships)
  return _impl_.ships_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Ship >*
GameState::mutable_ships() {
  // @@protoc_insertion_point(field_mutable_list:universe.GameState.ships)
  return &_impl_.ships_;
}
inline const ::universe::Ship& GameState::_internal_ships(int index) const {
  return _impl_.ships_.Get(index);
}
inline const ::universe::Ship& GameState::ships(int index) const {
  // @@protoc_insertion_point(field_get:universe.GameState.ships)
  return _internal_ships(index);
}
inline ::universe::Ship* GameState::_internal_add_ships() {
  return _impl_.ships_.Add();
}
inline ::universe::Ship* GameState::add_ships() {
  ::universe::Ship* _add = _internal_add_ships();
  // @@protoc_insertion_point(field_add:universe.GameState.ships)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Ship >&
GameState::ships() const {
  // @@protoc_insertion_point(field_list:universe.GameState.ships)
  return _impl_.ships_;
}

// repeated .universe.Planet planets = 2;
inline int GameState::_internal_planets_size() const {
  return _impl_.planets_.size();
}
inline int GameState::planets_size() const {
  return _internal_planets_size();
}
inline void GameState::clear_planets() {
  _impl_.planets_.Clear();
}
inline ::universe::Planet* GameState::mutable_planets(int index) {
  // @@protoc_insertion_point(field_mutable:universe.GameState.planets)
  return _impl_.planets_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Planet >*
GameState::mutable_planets() {
  // @@protoc_insertion_point(field_mutable_list:universe.GameState.planets)
  return &_impl_.planets_;
}
inline const ::universe::Planet& GameState::_internal_planets(int index) const {
  return _impl_.planets_.Get(index);
}
inline const ::universe::Planet& GameState::planets(int index) const {
  // @@protoc_insertion_point(field_get:universe.GameState.planets)
  return _internal_planets(index);
}
inline ::universe::Planet* GameState::_internal_add_planets() {
  return _impl_.planets_.Add();
}
inline ::universe::Planet* GameState::add_planets() {
  ::universe::Planet* _add = _internal_add_planets();
  // @@protoc_insertion_point(field_add:universe.GameState.planets)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Planet >&
GameState::planets() const {
  // @@protoc_insertion_point(field_list:universe.GameState.planets)
  return _impl_.planets_;
}

// repeated .universe.Trash trash = 3;
inline int GameState::_internal_trash_size() const {
  return _impl_.trash_.size();
}
inline int GameState::trash_size() const {
  return _internal_trash_size();
}
inline void GameState::clear_trash() {
  _impl_.trash_.Clear();
}
inline ::universe::Trash* GameState::mutable_trash(int index) {
  // @@protoc_insertion_point(field_mutable:universe.GameState.trash)
  return _impl_.trash_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Trash >*
GameState::mutable_trash() {
  // @@protoc_insertion_point(field_mutable_list:universe.GameState.trash)
  return &_impl_.trash_;
}
inline const ::universe::Trash& GameState::_internal_trash(int index) const {
  return _impl_.trash_.Get(index);
}
inline const ::universe::Trash& GameState::trash(int index) const {
  // @@protoc_insertion_point(field_get:universe.GameState.trash)
  return _internal_trash(index);
}
inline ::universe::Trash* GameState::_internal_add_trash() {
  return _impl_.trash_.Add();
}
inline ::universe::Trash* GameState::add_trash() {
  ::universe::Trash* _add = _internal_add_trash();
  // @@protoc_insertion_point(field_add:universe.GameState.trash)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::universe::Trash >&
GameState::trash() const {
  // @@protoc_insertion_point(field_list:universe.GameState.trash)
  return _impl_.trash_;
}

// int32 total_trash = 4;
inline void GameState::clear_total_trash() {
  _impl_.total_trash_ = 0;
}
inline int32_t GameState::_internal_total_trash() const {
  return _impl_.total_trash_;
}
inline int32_t GameState::total_trash() const {
  // @@protoc_insertion_point(field_get:universe.GameState.total_trash)
  return _internal_total_trash();
}
inline void GameState::_internal_set_total_trash(int32_t value) {
  
  _impl_.total_trash_ = value;
}
inline void GameState::set_total_trash(int32_t value) {
  _internal_set_total_trash(value);
  // @@protoc_insertion_point(field_set:universe.GameState.total_trash)
}

// -------------------------------------------------------------------

// Envelope

// .universe.Connect connect = 1;
inline bool Envelope::_internal_has_connect() const {
  return payload_case() == kConnect;
}
inline bool Envelope::has_connect() const {
  return _internal_has_connect();
}
inline void Envelope::set_has_connect() {
  _impl_._oneof_case_[0] = kConnect;
}
inline void Envelope::clear_connect() {
  if (_internal_has_connect()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.connect_;
    }
    clear_has_payload();
  }
}
inline ::universe::Connect* Envelope::release_connect() {
  // @@protoc_insertion_point(field_release:universe.Envelope.connect)
  if (_internal_has_connect()) {
    clear_has_payload();
    ::universe::Connect* temp = _impl_.payload_.connect_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::Connect& Envelope::_internal_connect() const {
  return _internal_has_connect()
      ? *_impl_.payload_.connect_
      : reinterpret_cast< ::universe::Connect&>(::universe::_Connect_default_instance_);
}
inline const ::universe::Connect& Envelope::connect() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.connect)
  return _internal_connect();
}
inline ::universe::Connect* Envelope::unsafe_arena_release_connect() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.connect)
  if (_internal_has_connect()) {
    clear_has_payload();
    ::universe::Connect* temp = _impl_.payload_.connect_;
    _impl_.payload_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_connect(::universe::Connect* connect) {
  clear_payload();
  if (connect) {
    set_has_connect();
    _impl_.payload_.connect_ = connect;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.connect)
}
inline ::universe::Connect* Envelope::_internal_mutable_connect() {
  if (!_internal_has_connect()) {
    clear_payload();
    set_has_connect();
    _impl_.payload_.connect_ = CreateMaybeMessage< ::universe::Connect >(GetArenaForAllocation());
  }
  return _impl_.payload_.connect_;
}
inline ::universe::Connect* Envelope::mutable_connect() {
  ::universe::Connect* _msg = _internal_mutable_connect();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.connect)
  return _msg;
}

// .universe.Move move = 2;
inline bool Envelope::_internal_has_move() const {
  return payload_case() == kMove;
}
inline bool Envelope::has_move() const {
  return _internal_has_move();
}
inline void Envelope::set_has_move() {
  _impl_._oneof_case_[0] = kMove;
}
inline void Envelope::clear_move() {
  if (_internal_has_move()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.move_;
    }
    clear_has_payload();
  }
}
inline ::universe::Move* Envelope::release_move() {
  // @@protoc_insertion_point(field_release:universe.Envelope.move)
  if (_internal_has_move()) {
    clear_has_payload();
    ::universe::Move* temp = _impl_.payload_.move_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::Move& Envelope::_internal_move() const {
  return _internal_has_move()
      ? *_impl_.payload_.move_
      : reinterpret_cast< ::universe::Move&>(::universe::_Move_default_instance_);
}
inline const ::universe::Move& Envelope::move() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.move)
  return _internal_move();
}
inline ::universe::Move* Envelope::unsafe_arena_release_move() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.move)
  if (_internal_has_move()) {
    clear_has_payload();
    ::universe::Move* temp = _impl_.payload_.move_;
    _impl_.payload_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_move(::universe::Move* move) {
  clear_payload();
  if (move) {
    set_has_move();
    _impl_.payload_.move_ = move;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.move)
}
inline ::universe::Move* Envelope::_internal_mutable_move() {
  if (!_internal_has_move()) {
    clear_payload();
    set_has_move();
    _impl_.payload_.move_ = CreateMaybeMessage< ::universe::Move >(GetArenaForAllocation());
  }
  return _impl_.payload_.move_;
}
inline ::universe::Move* Envelope::mutable_move() {
  ::universe::Move* _msg = _internal_mutable_move();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.move)
  return _msg;
}

// .universe.Response response = 3;
inline bool Envelope::_internal_has_response() const {
  return payload_case() == kResponse;
}
inline bool Envelope::has_response() const {
  return _internal_has_response();
}
inline void Envelope::set_has_response() {
  _impl_._oneof_case_[0] = kResponse;
}
inline void Envelope::clear_response() {
  if (_internal_has_response()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.response_;
    }
    clear_has_payload();
  }
}
inline ::universe::Response* Envelope::release_response() {
  // @@protoc_insertion_point(field_release:universe.Envelope.response)
  if (_internal_has_response()) {
    clear_has_payload();
    ::universe::Response* temp = _impl_.payload_.response_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::Response& Envelope::_internal_response() const {
  return _internal_has_response()
      ? *_impl_.payload_.response_
      : reinterpret_cast< ::universe::Response&>(::universe::_Response_default_instance_);
}
inline const ::universe::Response& Envelope::response() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.response)
  return _internal_response();
}
inline ::universe::Response* Envelope::unsafe_arena_release_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.response)
  if (_internal_has_response()) {
    clear_has_payload();
    ::universe::Response* temp = _impl_.payload_.response_;
    _impl_.payload_.response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_response(::universe::Response* response) {
  clear_payload();
  if (response) {
    set_has_response();
    _impl_.payload_.response_ = response;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.response)
}
inline ::universe::Response* Envelope::_internal_mutable_response() {
  if (!_internal_has_response()) {
    clear_payload();
    set_has_response();
    _impl_.payload_.response_ = CreateMaybeMessage< ::universe::Response >(GetArenaForAllocation());
  }
  return _impl_.payload_.response_;
}
inline ::universe::Response* Envelope::mutable_response() {
  ::universe::Response* _msg = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.response)
  return _msg;
}

// .universe.GameState game_state = 4;
inline bool Envelope::_internal_has_game_state() const {
  return payload_case() == kGameState;
}
inline bool Envelope::has_game_state() const {
  return _internal_has_game_state();
}
inline void Envelope::set_has_game_state() {
  _impl_._oneof_case_[0] = kGameState;
}
inline void Envelope::clear_game_state() {
  if (_internal_has_game_state()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.game_state_;
    }
    clear_has_payload();
  }
}
inline ::universe::GameState* Envelope::release_game_state() {
  // @@protoc_insertion_point(field_release:universe.Envelope.game_state)
  if (_internal_has_game_state()) {
    clear_has_payload();
    ::universe::GameState* temp = _impl_.payload_.game_state_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.game_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::universe::GameState& Envelope::_internal_game_state() const {
  return _internal_has_game_state()
      ? *_impl_.payload_.game_state_
      : reinterpret_cast< ::universe::GameState&>(::universe::_GameState_default_instance_);
}
inline const ::universe::GameState& Envelope::game_state() const {
  // @@protoc_insertion_point(field_get:universe.Envelope.game_state)
  return _internal_game_state();
}
inline ::universe::GameState* Envelope::unsafe_arena_release_game_state() {
  // @@protoc_insertion_point(field_unsafe_arena_release:universe.Envelope.game_state)
  if (_internal_has_game_state()) {
    clear_has_payload();
    ::universe::GameState* temp = _impl_.payload_.game_state_;
    _impl_.payload_.game_state_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Envelope::unsafe_arena_set_allocated_game_state(::universe::GameState* game_state) {
  clear_payload();
  if (game_state) {
    set_has_game_state();
    _impl_.payload_.game_state_ = game_state;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:universe.Envelope.game_state)
}
inline ::universe::GameState* Envelope::_internal_mutable_game_state() {
  if (!_internal_has_game_state()) {
    clear_payload();
    set_has_game_state();
    _impl_.payload_.game_state_ = CreateMaybeMessage< ::universe::GameState >(GetArenaForAllocation());
  }
  return _impl_.payload_.game_state_;
}
inline ::universe::GameState* Envelope::mutable_game_state() {
  ::universe::GameState* _msg = _internal_mutable_game_state();
  // @@protoc_insertion_point(field_mutable:universe.Envelope.game_state)
  return _msg;
}

inline bool Envelope::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void Envelope::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline Envelope::PayloadCase Envelope::payload_case() const {
  return Envelope::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace universe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fmessages_2eproto
